### ISSUE TITLE
Elastic.Ingest.Transport Nuget Package 0.5.5 references Elastic.Transport 0.4.16 causing bug

### ISSUE THREAD

**Issue by jasongerstorff** [elastic/elastic-ingest-dotnet#43]
Package version 0.5.5 references Elastic.Transport  >= 0.4.13. This is causing the package to use Elastic.Transport version 0.4.16 when installed. 

This is causing a bug in LibraryVersion class...it tries to call StoreVersion() in the base class VersionInfo, but that method does not exist in 0.4.16.  Possible to set the package to use 0.4.13 until fixed?

**Comment by Mpdreamz** [comment]
Thank you for raising this and apologies for this completely flying under my radar.

Addressing this as per: https://github.com/elastic/elastic-ingest-dotnet/pull/47
